### ISSUE TITLE
mDNS scan crashes on macOS apple silicon

### ISSUE THREAD

**Issue by git-elliot** [git-elliot/network_tools#44] opened 2022-07-28 15:56 UTC
I had the latest changes of your [dev](https://github.com/guyluz11/network_tools) branch @guyluz11 but the mDNS scan still breaks on IPv6 Addresses. I'm attaching the output here. 
```
Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
1%lo0
^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:131:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:142:16)
#2      int._parse (dart:core-patch/integers_patch.dart:103:12)
#3      int.parse (dart:core-patch/integers_patch.dart:65:12)
#4      new ActiveHost (package:network_tools/src/models/active_host.dart:19:20)
#5      MdnsScanner._findingMdnsWithIp (package:network_tools/src/mdns_scanner/mdns_scanner.dart:75:37)
<asynchronous suspension>
```
Output of `dns-sd -B _services._dns-sd._udp local`
```
Browsing for _services._dns-sd._udp.local
DATE: ---Thu 28 Jul 2022---
21:23:52.300  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
21:23:52.301  Add        3   4 .                    _tcp.local.          _airplay
21:23:52.301  Add        3   4 .                    _tcp.local.          _raop
21:23:52.301  Add        3   5 .                    _tcp.local.          _airplay
21:23:52.301  Add        3   5 .                    _tcp.local.          _raop
21:23:52.301  Add        3   1 .                    _tcp.local.          _airplay
21:23:52.301  Add        3   1 .                    _tcp.local.          _raop
21:23:52.301  Add        3  11 .                    _tcp.local.          _airplay
21:23:52.301  Add        3  11 .                    _tcp.local.          _raop
21:23:52.301  Add        2  11 .                    _udp.local.          _mi-connect
```
Output of `dns-sd -B _ipp._tcp local`

```
Browsing for _ipp._tcp.local
DATE: ---Thu 28 Jul 2022---
21:25:36.057  ...STARTING...
```

**Comment by guyluz11** [comment] 2022-07-28 18:28
Hi
I have included a fix for that in my last pr, please test again and close it if you cannot reproduce it.

**Closed** 2022-07-29 04:09 UTC
