### ISSUE TITLE
OSError (OS Error: Too many open files, errno = 24)

### ISSUE THREAD

**Issue by helenburns** [git-elliot/network_tools#48] opened 2022-08-02 14:33 UTC
I'm running a new template Flutter application and using the example/port_scan.dart code but when I run it on my iOS simulator I'm getting the error `OSError (OS Error: Too many open files, errno = 24)`

I am able to run the host and mdns examples fine. So I'm not sure what I'm doing wrong here?

**Comment by git-elliot** [comment] 2022-08-02 15:28
Try providing a shorter port range.

**Comment by helenburns** [comment] 2022-08-02 15:39
I tried limiting it from 1 to 100 and it did the same?

**Comment by git-elliot** [comment] 2022-08-02 17:11
Internet says ~250 files can be opened at once in iOS byt depends from device to device. What are your views @guyluz11 ?

**Comment by guyluz11** [comment] 2022-08-02 18:07
@helenburns I would love to have more information.

What iOS version is on the emulator.

Did it worked on a real iOS device?.

Does the log contain more information then what you copied?, for example on what file and line did the code crash?.

**Comment by Stausssi** [comment] 2022-08-02 21:17
I'm also getting the same error while discovering the entire subnet (from .1 to .254) on a single port only. Running on a iPhone 13 Pro with iOS 15.5 (latest). I suppose that every device will be discovered in a separate process thus opening a new file, just a guess tho :)

I can't provide the entire error log right now I hope the picture is sufficient:
![image](https://user-images.githubusercontent.com/33755707/182474888-6e33f5a6-4c46-4158-bb4d-dd9169a09bb4.png)

**Hotfix** (for @helenburns)
It can be fixed by manually iteration over the subnet and checking whether the port is active for every device. Makes it way slower tho (even withthe very short timeout) since it's run iteratively. Example:
```dart
for (int i = 1; i < 255; i++) {
  var port = PortScanner.isOpen(
    "$subnet.$i",
    PORT,
    timeout: const Duration(milliseconds: 100),
  );

  // Check the OpenPort-object and do your custom stuff ...
}
```

**Comment by Stausssi** [comment] 2022-08-02 21:26
Sorry, bad wording from myself:
A `process` in this case would be a separate, parallel socket connection to each device in the entire subnet. And since Socket connections are handled as files, we get the explained error message

**Comment by git-elliot** [comment] 2022-08-06 11:22
@helenburns Check dev branch code if the issue is fixed now then close this.

**Closed** 2022-08-06 16:03 UTC
